// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-uzgJU9rdseR0FmflMkXL2pJDPQPmS0w',
    appId: '1:646547311187:web:636457d5fa2add563794a6',
    messagingSenderId: '646547311187',
    projectId: 'studyapp-b31e2',
    authDomain: 'studyapp-b31e2.firebaseapp.com',
    storageBucket: 'studyapp-b31e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzixg2V4WEOhlnPRzkQa49_nqj8F9FPes',
    appId: '1:646547311187:android:81a04c5607edd85d3794a6',
    messagingSenderId: '646547311187',
    projectId: 'studyapp-b31e2',
    storageBucket: 'studyapp-b31e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvKJgPKogdO1KtB-lfwZGGKBITTR3UQg',
    appId: '1:646547311187:ios:45ad7e5f910ed07d3794a6',
    messagingSenderId: '646547311187',
    projectId: 'studyapp-b31e2',
    storageBucket: 'studyapp-b31e2.firebasestorage.app',
    iosBundleId: 'com.example.studdyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-uzgJU9rdseR0FmflMkXL2pJDPQPmS0w',
    appId: '1:646547311187:web:c780138a23a428513794a6',
    messagingSenderId: '646547311187',
    projectId: 'studyapp-b31e2',
    authDomain: 'studyapp-b31e2.firebaseapp.com',
    storageBucket: 'studyapp-b31e2.firebasestorage.app',
  );
}
